-- In database 'postgres'
-- Reference: https://github.com/citusdata/pg_cron/blob/main/README.md
CREATE EXTENSION IF NOT EXISTS pg_cron;
SELECT cron.schedule_in_database(
	'update_recent_status',
	'0 0 8 * *',
    $$
	UPDATE video_metadata
	SET	recent = upload_date >= date_trunc('month', CURRENT_DATE) - interval '1 month' - interval '1 day'
	WHERE upload_date >= date_trunc('month', CURRENT_DATE) - interval '4 month';
	$$,
    'smols_form'
);


-- In form database
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS "user" (
	id TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS video_metadata (
	id BIGSERIAL PRIMARY KEY,
	video_id TEXT NOT NULL,
	thumbnail TEXT NOT NULL,
	title TEXT NOT NULL,
	uploader TEXT NOT NULL,
	uploader_id TEXT NOT NULL,
	upload_date DATE NOT NULL,
	duration INT,
	platform TEXT NOT NULL,
	recent BOOL NOT NULL,
	whitelisted BOOL NOT NULL DEFAULT FALSE,
	source BIGINT,
	UNIQUE (video_id, platform),
	FOREIGN KEY (source) REFERENCES video_metadata (id)
);

CREATE INDEX IF NOT EXISTS trgm_idx ON video_metadata
USING GIN (title gin_trgm_ops)
WHERE recent AND whitelisted;

CREATE TABLE IF NOT EXISTS ballot_item (
	user_id TEXT NOT NULL,
	metadata_id BIGINT NOT NULL,
	creation_date TIMESTAMP NOT NULL,
	index INT NOT NULL,
	PRIMARY KEY (user_id, index),
	FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
	FOREIGN KEY (metadata_id) REFERENCES video_metadata (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS playlist (
	id TEXT PRIMARY KEY,
	owner_id TEXT,
	thumbnail TEXT,
	name TEXT,
	description TEXT,
	last_accessed DATE
);

CREATE TABLE IF NOT EXISTS playlist_item (
	id SERIAL PRIMARY KEY,
	playlist_id TEXT NOT NULL,
	metadata_id BIGINT NOT NULL,
	FOREIGN KEY (playlist_id) REFERENCES playlist (id) ON DELETE CASCADE,
	FOREIGN KEY (metadata_id) REFERENCES video_metadata (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS label_config (
	name TEXT NOT NULL,
	type TEXT NOT NULL,
	details TEXT NOT NULL,
	trigger TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS manual_label (
	metadata_id BIGINT PRIMARY KEY,
	label TEXT NOT NULL,
	content TEXT NOT NULL,
	FOREIGN KEY (metadata_id) REFERENCES video_metadata (id) ON DELETE CASCADE
);

-- Changes from previous version
ALTER TABLE video_metadata RENAME id TO video_id;
ALTER TABLE video_metadata ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE video_metadata ALTER COLUMN id SET NOT NULL;

ALTER TABLE manual_label ADD COLUMN metadata_id BIGINT NOT NULL;
UPDATE manual_label m
	SET metadata_id = v.id
	FROM video_metadata v
	WHERE v.video_id = m.video_id AND v.platform = m.platform;
ALTER TABLE manual_label DROP CONSTRAINT manual_label_video_id_platform_fkey;
ALTER TABLE manual_label DROP COLUMN platform, DROP COLUMN video_id;

ALTER TABLE playlist_item ADD COLUMN metadata_id BIGINT NOT NULL;
UPDATE playlist_item p
	SET metadata_id = v.id
	FROM video_metadata v
	WHERE v.video_id = p.video_id AND v.platform = p.platform;
ALTER TABLE playlist_item DROP CONSTRAINT playlist_item_video_id_platform_fkey;
ALTER TABLE playlist_item DROP COLUMN platform, DROP COLUMN video_id;

ALTER TABLE ballot_item ADD COLUMN metadata_id BIGINT NOT NULL;
UPDATE ballot_item b
	SET metadata_id = v.id
	FROM video_metadata v
	WHERE v.video_id = b.video_id AND v.platform = b.platform;
ALTER TABLE ballot_item DROP CONSTRAINT ballot_item_video_id_platform_fkey;
ALTER TABLE ballot_item DROP COLUMN platform, DROP COLUMN video_id;

ALTER TABLE video_metadata DROP CONSTRAINT video_metadata_pkey;
ALTER TABLE video_metadata ADD PRIMARY KEY (id);
ALTER TABLE video_metadata ADD UNIQUE (video_id, platform);

ALTER TABLE playlist_item ADD FOREIGN KEY (metadata_id) REFERENCES video_metadata (id) ON DELETE CASCADE;
ALTER TABLE ballot_item ADD FOREIGN KEY (metadata_id) REFERENCES video_metadata (id) ON DELETE CASCADE;
ALTER TABLE manual_label ADD FOREIGN KEY (metadata_id) REFERENCES video_metadata (id) ON DELETE CASCADE;
ALTER TABLE manual_label ADD PRIMARY KEY (metadata_id);

ALTER TABLE video_metadata DROP COLUMN source;
ALTER TABLE video_metadata ADD COLUMN source BIGINT;
ALTER TABLE video_metadata ADD FOREIGN KEY (source) REFERENCES video_metadata (id) ON DELETE SET NULL;
