-- In database 'postgres'
-- Reference: https://github.com/citusdata/pg_cron/blob/main/README.md
CREATE EXTENSION IF NOT EXISTS pg_cron;
SELECT cron.schedule_in_database(
	'update_recent_status',
	'0 0 8 * *',
    $$
	UPDATE video_metadata
	SET	recent = FALSE
	WHERE recent AND upload_date < date_trunc('month', CURRENT_DATE) - interval '1 day';
	$$,
    'smols_form'
);


-- In form database
CREATE EXTENSION IF NOT EXISTS pg_trgm;

ALTER DATABASE smols_form
	SET pg_trgm.similarity_threshold = 0.6;


CREATE TABLE IF NOT EXISTS "user" (
	id TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS video_metadata (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	video_id TEXT NOT NULL,
	thumbnail TEXT NOT NULL,
	title TEXT NOT NULL,
	uploader TEXT NOT NULL,
	uploader_id TEXT NOT NULL,
	upload_date DATE NOT NULL,
	duration INT,
	platform TEXT NOT NULL,
	recent BOOL NOT NULL,
	searchable BOOL,
	source BIGINT,
	FOREIGN KEY (source) REFERENCES video_metadata (id) ON DELETE SET NULL,
	UNIQUE (video_id, platform),
	CHECK (source <> id)
);

CREATE INDEX IF NOT EXISTS title_trgm_idx ON video_metadata
	USING GIN (title gin_trgm_ops)
	WHERE recent AND searchable;

CREATE INDEX IF NOT EXISTS uploader_trgm_idx ON video_metadata
	USING GIN (uploader gin_trgm_ops)
	WHERE recent AND searchable;


CREATE TABLE IF NOT EXISTS ballot_item (
	user_id TEXT NOT NULL,
	metadata_id BIGINT NOT NULL,
	creation_date TIMESTAMP NOT NULL,
	index INT NOT NULL,
	PRIMARY KEY (user_id, index),
	FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
	FOREIGN KEY (metadata_id) REFERENCES video_metadata (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS playlist (
	id TEXT PRIMARY KEY,
	owner_id TEXT,
	thumbnail TEXT,
	name TEXT,
	description TEXT,
	last_accessed DATE
);

CREATE TABLE IF NOT EXISTS playlist_item (
	id SERIAL PRIMARY KEY,
	playlist_id TEXT NOT NULL,
	metadata_id BIGINT NOT NULL,
	FOREIGN KEY (playlist_id) REFERENCES playlist (id) ON DELETE CASCADE,
	FOREIGN KEY (metadata_id) REFERENCES video_metadata (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS label_config (
	name TEXT NOT NULL,
	type TEXT NOT NULL,
	details TEXT NOT NULL,
	trigger TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS manual_label (
	metadata_id BIGINT PRIMARY KEY,
	eligible BOOL NOT NULL,
	reason TEXT,
	FOREIGN KEY (metadata_id) REFERENCES video_metadata (id) ON DELETE CASCADE,
	CHECK (
		eligible OR
		(reason IS NOT NULL AND length(trim(reason)) > 0)
	)
);


-- Changes from previous version
DROP FUNCTION title_search_metadata;

CREATE OR REPLACE FUNCTION video_search(
	q TEXT,
	lim INT DEFAULT 3
)
RETURNS SETOF video_metadata
LANGUAGE sql
STABLE
AS $$
    WITH vm_score AS (
        SELECT vm, GREATEST(word_similarity(q, title), word_similarity(q, uploader)) AS sim
        FROM video_metadata vm
        WHERE recent
			AND searchable
			AND (q <% title OR q <% uploader)
    )
    SELECT (vm).*
    FROM vm_score
    ORDER BY sim DESC
    LIMIT lim;
$$;

ALTER INDEX trgm_idx RENAME TO title_trgm_idx;

CREATE INDEX IF NOT EXISTS uploader_trgm_idx ON video_metadata
	USING GIN (uploader gin_trgm_ops)
	WHERE recent AND searchable;

ALTER DATABASE smols_form
	SET pg_trgm.similarity_threshold = 0.6;
