-- Execute in database 'postgres'
-- Reference: https://github.com/citusdata/pg_cron/blob/main/README.md
CREATE EXTENSION IF NOT EXISTS pg_cron;
SELECT cron.schedule_in_database(
	'update_recent_status',
	'0 0 8 * *',
    $$
	UPDATE video_metadata
	SET	recent = FALSE
	WHERE recent AND upload_date < date_trunc('month', CURRENT_DATE) - interval '1 day';
	$$,
    'smols_form'
);


-- Execute in form database
CREATE EXTENSION IF NOT EXISTS pg_trgm;

ALTER DATABASE smols_form
	SET pg_trgm.similarity_threshold = 0.6;


-- Types
CREATE TYPE video_platform2 AS ENUM(
	'YouTube',
    'Bilibili',
    'Bluesky',
    'Dailymotion',
	'Derpibooru',
    'Instagram',
    'Newgrounds',
    'Odysee',
    'PonyTube',
    'ThisHorsieRocks',
    'Tiktok',
    'Twitter',
    'Vimeo'
);


-- Tables
CREATE TABLE IF NOT EXISTS "user" (
	id TEXT PRIMARY KEY
);


CREATE TABLE IF NOT EXISTS creator (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	channel_id TEXT NOT NULL,
	platform video_platform NOT NULL,
	channel_name TEXT NOT NULL,
	pfp_url TEXT,
	alias_of BIGINT,
	last_updated DATE NOT NULL DEFAULT CURRENT_DATE,
	FOREIGN KEY (alias_of) REFERENCES creator,
	UNIQUE (channel_id, platform)
);


CREATE TABLE IF NOT EXISTS video_metadata (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	creator_id BIGINT NOT NULL,
	video_id TEXT NOT NULL,
	thumbnail TEXT NOT NULL,
	title TEXT NOT NULL,
	uploader TEXT NOT NULL,
	uploader_id TEXT NOT NULL,
	upload_date DATE NOT NULL,
	duration INT,
	platform video_platform NOT NULL,
	recent BOOL NOT NULL,
	searchable BOOL,
	source BIGINT,
	FOREIGN KEY (source) REFERENCES video_metadata (id) ON DELETE SET NULL,
	FOREIGN KEY (creator_id) REFERENCES creator,
	UNIQUE (video_id, platform),
	CHECK (source <> id)
);

CREATE INDEX IF NOT EXISTS title_trgm_idx ON video_metadata
	USING GIN (title gin_trgm_ops)
	WHERE recent AND searchable;

CREATE INDEX IF NOT EXISTS uploader_trgm_idx ON video_metadata
	USING GIN (uploader gin_trgm_ops)
	WHERE recent AND searchable;


CREATE TABLE IF NOT EXISTS ballot_item (
	user_id TEXT NOT NULL,
	metadata_id BIGINT NOT NULL,
	creation_date TIMESTAMP NOT NULL,
	voting_period DATE NOT NULL,
	index INT NOT NULL,
	PRIMARY KEY (user_id, index),
	FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
	FOREIGN KEY (metadata_id) REFERENCES video_metadata (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS playlist (
	id TEXT PRIMARY KEY,
	owner_id TEXT,
	thumbnail TEXT,
	name TEXT,
	description TEXT,
	last_accessed DATE
);

CREATE TABLE IF NOT EXISTS playlist_item (
	id SERIAL PRIMARY KEY,
	playlist_id TEXT NOT NULL,
	metadata_id BIGINT NOT NULL,
	FOREIGN KEY (playlist_id) REFERENCES playlist (id) ON DELETE CASCADE,
	FOREIGN KEY (metadata_id) REFERENCES video_metadata (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS manual_label (
	metadata_id BIGINT PRIMARY KEY,
	eligible BOOL NOT NULL,
	reason TEXT,
	FOREIGN KEY (metadata_id) REFERENCES video_metadata (id) ON DELETE CASCADE,
	CHECK (
		eligible OR
		(reason IS NOT NULL AND length(trim(reason)) > 0)
	)
);


-- Functions
CREATE OR REPLACE FUNCTION video_search(q TEXT, lim INT DEFAULT 3)
RETURNS TABLE (
	video_metadata video_metadata,
	creator creator
)
LANGUAGE sql
STABLE
AS $$
	SELECT vm, c
		FROM video_metadata vm JOIN creator c
			ON vm.creator_id = c.id
		WHERE vm.recent
			AND vm.searchable
			AND (q <% title OR q <% channel_name)
	ORDER BY GREATEST(
		word_similarity(q, title),
		word_similarity(q, channel_name)
	) DESC
	LIMIT lim;
$$;


CREATE OR REPLACE FUNCTION get_video_votes(m_id BIGINT)
RETURNS INT
LANGUAGE sql
STABLE
AS $$
    SELECT COUNT(DISTINCT user_id)
	FROM ballot_item
		WHERE metadata_id = m_id;
$$;

-- Changes from previous version
ALTER TABLE video_metadata ADD COLUMN creator_id BIGINT;
ALTER TABLE video_metadata ADD FOREIGN KEY (creator_id) REFERENCES creator;

ALTER TABLE video_metadata ADD COLUMN tmp video_platform;
UPDATE video_metadata SET tmp = platform::video_platform;
ALTER TABLE video_metadata DROP COLUMN platform;
ALTER TABLE video_metadata RENAME COLUMN tmp TO platform;
ALTER TABLE video_metadata ALTER COLUMN platform SET NOT NULL;
ALTER TABLE video_metadata ADD UNIQUE (video_id, platform);

ALTER TABLE video_metadata DROP COLUMN uploader;
ALTER TABLE video_metadata DROP COLUMN uploader_id;

ALTER TABLE ballot_item ADD COLUMN voting_period DATE;
UPDATE ballot_item SET voting_period = DATE_TRUNC('month', CURRENT_DATE);

WITH recents AS (
    SELECT b.user_id, b.index b_index
    FROM video_metadata v
    JOIN ballot_item b
      ON b.metadata_id = v.id
    WHERE v.recent
)
DELETE FROM ballot_item b
WHERE NOT EXISTS (
    SELECT 1
    FROM recents r
    WHERE r.user_id = b.user_id
      AND r.b_index = b.index
);

SELECT * FROM video_metadata WHERE creator_id IS NULL;
DELETE FROM video_metadata WHERE creator_id IS NULL;
ALTER TABLE video_metadata ALTER COLUMN creator_id SET NOT NULL;

ALTER TABLE ballot_item ALTER COLUMN voting_period SET NOT NULL;

DROP FUNCTION video_search; -- Then recreate

